"""initial_schema

Revision ID: ea4916806888
Revises: 
Create Date: 2026-03-18 20:27:57.804898
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea4916806888'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_rating', sa.SmallInteger(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_sources_category', 'sources', ['category'], unique=False)
    op.create_index('idx_sources_status', 'sources', ['status'], unique=False)
    op.create_table('source_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_changelog_source', 'source_change_log', ['source_id'], unique=False)
    op.create_table('sub_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('user_rating', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('content_count', sa.Integer(), nullable=False),
    sa.Column('avg_quality', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'handle', name='uq_sub_source_handle')
    )
    op.create_index('idx_sub_sources_source', 'sub_sources', ['source_id'], unique=False)
    op.create_index('idx_sub_sources_status', 'sub_sources', ['status'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('sub_source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('topic_tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['sub_source_id'], ['sub_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_url')
    )
    op.create_index('idx_content_published', 'content_items', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index('idx_content_relevance', 'content_items', [sa.literal_column('relevance_score DESC')], unique=False)
    op.create_index('idx_content_source', 'content_items', ['source_id'], unique=False)
    op.create_index('idx_content_sub_source', 'content_items', ['sub_source_id'], unique=False)
    op.create_index('idx_content_tags', 'content_items', ['topic_tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_content_type', 'content_items', ['content_type'], unique=False)
    op.create_table('feedback_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_content', 'feedback_log', ['content_id'], unique=False)
    op.create_index('idx_feedback_created', 'feedback_log', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feedback_created', table_name='feedback_log')
    op.drop_index('idx_feedback_content', table_name='feedback_log')
    op.drop_table('feedback_log')
    op.drop_index('idx_content_type', table_name='content_items')
    op.drop_index('idx_content_tags', table_name='content_items', postgresql_using='gin')
    op.drop_index('idx_content_sub_source', table_name='content_items')
    op.drop_index('idx_content_source', table_name='content_items')
    op.drop_index('idx_content_relevance', table_name='content_items')
    op.drop_index('idx_content_published', table_name='content_items')
    op.drop_table('content_items')
    op.drop_index('idx_sub_sources_status', table_name='sub_sources')
    op.drop_index('idx_sub_sources_source', table_name='sub_sources')
    op.drop_table('sub_sources')
    op.drop_index('idx_changelog_source', table_name='source_change_log')
    op.drop_table('source_change_log')
    op.drop_index('idx_sources_status', table_name='sources')
    op.drop_index('idx_sources_category', table_name='sources')
    op.drop_table('sources')
    op.drop_table('filter_presets')
    # ### end Alembic commands ###
